//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Create.CSP.GitHub.Reporting.Database.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CSPDatabaseModelEntities : DbContext
    {
        public CSPDatabaseModelEntities()
            : base("name=CSPDatabaseModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivationReport> ActivationReports { get; set; }
        public virtual DbSet<CorrelationId> CorrelationIds { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customers_History> Customers_History { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<Domains_History> Domains_History { get; set; }
        public virtual DbSet<MarketingCampaign> MarketingCampaigns { get; set; }
        public virtual DbSet<MarketingCampaignsCustomer> MarketingCampaignsCustomers { get; set; }
        public virtual DbSet<SubscribedSKU> SubscribedSKUs { get; set; }
        public virtual DbSet<SubscribedSKUs_History> SubscribedSKUs_History { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<Subscriptions_History> Subscriptions_History { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
    
        public virtual int GetCorrelationIdFromContext(ObjectParameter correlationId)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetCorrelationIdFromContext", correlationId);
        }
    
        public virtual int SetCorrelationIdToContext(string correlationId)
        {
            var correlationIdParameter = correlationId != null ?
                new ObjectParameter("CorrelationId", correlationId) :
                new ObjectParameter("CorrelationId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetCorrelationIdToContext", correlationIdParameter);
        }
    }
}
