//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Create.CSP.GitHub.Reporting.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers_History()
        {
            this.Domains_History = new HashSet<Domains_History>();
            this.SubscribedSKUs_History = new HashSet<SubscribedSKUs_History>();
            this.Subscriptions_History = new HashSet<Subscriptions_History>();
        }
    
        public System.Guid CorrelationId { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid TenantId { get; set; }
        public string CompanyName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Region { get; set; }
        public string State { get; set; }
    
        public virtual CorrelationId CorrelationId1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Domains_History> Domains_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscribedSKUs_History> SubscribedSKUs_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscriptions_History> Subscriptions_History { get; set; }
    }
}
