//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Create.CSP.GitHub.Reporting.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingCampaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarketingCampaign()
        {
            this.MarketingCampaignsCustomers = new HashSet<MarketingCampaignsCustomer>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketingCampaignsCustomer> MarketingCampaignsCustomers { get; set; }
    }
}
