//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Create.CSP.GitHub.Reporting.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions_History
    {
        public System.Guid CorrelationId { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid CustomerId { get; set; }
        public string SubscribedSKUId { get; set; }
        public string Status { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual CorrelationId CorrelationId1 { get; set; }
        public virtual Customers_History Customers_History { get; set; }
        public virtual SubscribedSKUs_History SubscribedSKUs_History { get; set; }
    }
}
